export const Posts = [
  {
    id: 1,
    desc: "Human sins and humanity suffers",
    photo: "post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 190,
    comment: 73,
  },
  {
    id: 2,
    desc: "Life is easy when you dont care",
    photo: "post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 19,
    comment: 27,
  },
  {
    id: 3,
    photo: "post/3.jpeg",
    date: "7 mins ago",
    userId: 3,
    like: 1,
    comment: 73,
  },
  {
    id: 4,
    desc: "Never post your feelings, just never",
    photo: "post/4.jpeg",
    date: "53 mins ago",
    userId: 4,
    like: 10,
    comment: 7,
  },
  {
    id: 5,
    desc: "Just make it happen",
    photo: "post/5.jpeg",
    date: "30 mins ago",
    userId: 5,
    like: 40,
    comment: 13,
  },
  {
    id: 6,
    desc: "Human sins and humanity suffers",
    photo: "post/6.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 190,
    comment: 73,
  },
  {
    id: 7,
    desc: "Life is easy when you dont care",
    photo: "post/7.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 19,
    comment: 27,
  },
  {
    id: 8,
    photo: "post/8.jpeg",
    date: "7 mins ago",
    userId: 3,
    like: 1,
    comment: 73,
  },
  {
    id: 9,
    desc: "Never post your feelings, just never",
    photo: "post/9.jpeg",
    date: "53 mins ago",
    userId: 4,
    like: 10,
    comment: 7,
  },
  {
    id: 10,
    desc: "Just make it happen",
    photo: "post/10.jpeg",
    date: "30 mins ago",
    userId: 5,
    like: 40,
    comment: 13,
  },
];

export const Users = [
  {
    id: 1,
    profilePicture: "person/1.jpeg",
    username: "Elon Musk",
  },
  {
    id: 2,
    profilePicture: "person/2.jpeg",
    username: "Bill Gates",
  },
  {
    id: 3,
    profilePicture: "person/3.jpeg",
    username: "Jeff Bejos",
  },
  {
    id: 4,
    profilePicture: "person/4.jpeg",
    username: "Steve Jobs",
  },
  {
    id: 5,
    profilePicture: "person/5.jpeg",
    username: "Robert Downy Jr.",
  },
  {
    id: 6,
    profilePicture: "person/1.jpeg",
    username: "Elon Musk",
  },
  {
    id: 7,
    profilePicture: "person/2.jpeg",
    username: "Bill Gates",
  },
  {
    id: 8,
    profilePicture: "person/3.jpeg",
    username: "Jeff Bejos",
  },
  {
    id: 9,
    profilePicture: "person/4.jpeg",
    username: "Steve Jobs",
  },
  {
    id: 10,
    profilePicture: "person/5.jpeg",
    username: "Robert Downy Jr.",
  },
];
